image: $CI_REGISTRY/devops/docker-php-ci:latest

include:
    - project: 'devops/shared-pipelines'
      file: '/jobs-common.yml'
    - project: 'devops/shared-pipelines'
      file: '/jobs-composer-install.yml'
    - project: 'devops/shared-pipelines'
      file: '/jobs-php-static-analysis.yml'

variables:
    phpcs_standard: "PSR12"
    phpunit_config: "test/"
    phpcs_ignore:   "vendor/,test/"
    phpmd_ignore:   "vendor/,test/"

