image: lovullo/php-ci

include:
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-common.yml'
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-composer-install.yml'
    - 'http://devops.pages.lovullo.com/shared-pipelines/jobs-php-static-analysis.yml'

variables:
    phpunit_config: "test/"
    phpcs_ignore:   "vendor/,test/"
    phpmd_ignore:   "vendor/,test/"

