#!/bin/bash
#
#  Copyright (C) 2016 LoVullo Associates, Inc.
#
#  This file is part of libliza-php.
#
#  libliza-php is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Checks to ensure that each PHP class is mentioned in the UML diagram to
# keep documentation up to date.
##

declare -r rootpath="$( dirname $0 )/.."
declare -r libpath="$rootpath/src"
declare -r umlpath="$rootpath/doc/diagrams/class-uml.dia"

# retrieve the names of the classes in lib/ (they will always start with a
# capital letter)
classes=$( find $libpath -name '*.php' -exec basename {} \; \
  | grep -P ^[A-Z] \
  | sed 's/\.php$//'
)

declare -i fail=0

# check UML diagram for each class
for class in $classes; do
  grep -q "$class" "$umlpath" || {
    echo "Missing $class in $( basename $umlpath )"
    ((fail++))
  }
done

# if there were any missing classes, exit with a non-zero status to indicate
# failure
if [ $fail -gt 0 ]; then
  echo "$fail failure(s)"
  exit 1
fi

